models:

  LogisticRegression_L1:
    class_path: sklearn.linear_model.LogisticRegression
    params:
      penalty: ["l1"]
      solver: ["liblinear"]
      max_iter: [1000]
      C: [0.01, 0.1, 1, 10, 100, 1000]
      class_weight: ["balanced", null]

  LogisticRegression_L2:
    class_path: sklearn.linear_model.LogisticRegression
    params:
      penalty: ["l2"]
      solver: ["liblinear"]
      max_iter: [1000]
      C: [0.01, 0.1, 1, 10, 100, 1000]
      class_weight: ["balanced", null]

  SVC:
    class_path: sklearn.svm.SVC
    params:
      kernel: ["linear", "rbf"]
      C: [0.1, 1, 10, 100]
      gamma: ["scale", "auto"]
      class_weight: ["balanced", null]

  RandomForestClassifier:
    class_path: sklearn.ensemble.RandomForestClassifier
    params:
      n_estimators: [100, 200, 500]
      max_depth: [5, 10, 20, null]
      class_weight: ["balanced", null]

  XGBClassifier:
    class_path: xgboost.XGBClassifier
    params:
      n_estimators: [100, 200]
      max_depth: [5, 10, 20]
      learning_rate: [0.01, 0.1, 0.2]
      tree_method: ["hist"]
      device: ["cuda:0"]
      eval_metric: ["logloss"]
      verbosity: [0]

  SkorchMLPClassifier:
    class_path: skorch.NeuralNetClassifier
    params:
      module: ["src.models.module_MLP.MLP"]
      module__input_dim: [94241]
      max_epochs: [20, 50]
      lr: [0.001, 0.0003]
      batch_size: [32]
      device: ["cuda"]
      optimizer: ["torch.optim.Adam"]
      criterion: ["torch.nn.CrossEntropyLoss"] # classification
      verbose: [0]

  SkorchMLPClassifierOther:
    class_path: skorch.NeuralNetClassifier
    params:
      module: ["src.models.module_MLP.MLP"]
      module__input_dim: [94241]
      max_epochs: [50, 100]
      lr: [0.001, 0.0003, 0.0001]
      batch_size: [64, 128]
      device: ["cuda"]
      optimizer__weight_decay: [0.0001] # régularisation L2 optimale
      optimizer: ["torch.optim.Adam"]
      criterion: ["torch.nn.CrossEntropyLoss"] # classification
      verbose: [0]

  LGBMClassifier:
    class_path: lightgbm.LGBMClassifier
    params:
      boosting_type: ["gbdt"]
      n_estimators: [100, 200]
      max_depth: [5, 10, -1]
      num_leaves: [31, 64]
      learning_rate: [0.01, 0.1]
      class_weight: ["balanced", null]
      device: ["gpu"]         
      gpu_platform_id: [0]    # facultatif, mais explicite si plusieurs GPUs
      gpu_device_id: [0]
      verbose: [-1]